project:
  type: website
  output-dir: docs

website:
  title: "Katy Prudic, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: outreach.qmd
        text: Outreach
      - href: people.qmd
        text: People
      - href: cv.qmd
        text: CV


format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

