project:
  type: website
  output-dir: docs

website:
  title: "Katy Prudic, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: people.qmd
        text: People

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

